//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskSpace.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Ctrl {
            get {
                return ((bool)(this["Ctrl"]));
            }
            set {
                this["Ctrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Shift {
            get {
                return ((bool)(this["Shift"]));
            }
            set {
                this["Shift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WindowsKey {
            get {
                return ((bool)(this["WindowsKey"]));
            }
            set {
                this["WindowsKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int HotKey {
            get {
                return ((int)(this["HotKey"]));
            }
            set {
                this["HotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Alt {
            get {
                return ((bool)(this["Alt"]));
            }
            set {
                this["Alt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstRun {
            get {
                return ((bool)(this["FirstRun"]));
            }
            set {
                this["FirstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AltTabHook {
            get {
                return ((bool)(this["AltTabHook"]));
            }
            set {
                this["AltTabHook"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RunAsAdmin {
            get {
                return ((bool)(this["RunAsAdmin"]));
            }
            set {
                this["RunAsAdmin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoSwitch {
            get {
                return ((bool)(this["AutoSwitch"]));
            }
            set {
                this["AutoSwitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableHotKey {
            get {
                return ((bool)(this["EnableHotKey"]));
            }
            set {
                this["EnableHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>notepad++.exe</string>
  <string>notepad.exe</string>
  <string>sublime.exe</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Apps_E {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Apps_E"]));
            }
            set {
                this["Apps_E"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>devenv.exe</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Apps_V {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Apps_V"]));
            }
            set {
                this["Apps_V"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>winword.exe</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Apps_W {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Apps_W"]));
            }
            set {
                this["Apps_W"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>excel.exe</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Apps_X {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Apps_X"]));
            }
            set {
                this["Apps_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>rubymine64.exe</string>\r\n  <string>rubymine.exe</string>\r\n</ArrayOfString>" +
            "")]
        public global::System.Collections.Specialized.StringCollection Apps_R {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Apps_R"]));
            }
            set {
                this["Apps_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>pbidesktop.exe</string>
  <string>postman.exe</string>
  <string>powerpnt.exe</string>
  <string>pycharm64.exe</string>
  <string>pycharm.exe</string>
  <string>mspaint.exe</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Apps_P {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Apps_P"]));
            }
            set {
                this["Apps_P"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>ssms.exe</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Apps_Q {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Apps_Q"]));
            }
            set {
                this["Apps_Q"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>snippingtool.exe</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Apps_S {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Apps_S"]));
            }
            set {
                this["Apps_S"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>taskmgr.exe</string>\r\n  <string>teams.exe</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Apps_T {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Apps_T"]));
            }
            set {
                this["Apps_T"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>outlook.exe</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Apps_O {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Apps_O"]));
            }
            set {
                this["Apps_O"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" />")]
        public global::System.Collections.Specialized.StringCollection Apps_A {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Apps_A"]));
            }
            set {
                this["Apps_A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>msedge.exe</string>
  <string>chrome.exe</string>
  <string>firefox.exe</string>
  <string>vivaldi.exe</string>
  <string>brave.exe</string>
  <string>opera.exe</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Apps_B {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Apps_B"]));
            }
            set {
                this["Apps_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>cmd.exe</string>
  <string>bcompare.exe</string>
  <string>calc.exe</string>
  <string>calculator.exe</string>
  <string>countuptimer.exe</string>
  <string>merge.exe</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Apps_C {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Apps_C"]));
            }
            set {
                this["Apps_C"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Apps_D {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Apps_D"]));
            }
            set {
                this["Apps_D"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>explorer.exe</string>
  <string>totalcmd.exe</string>
  <string>totalcmd64.exe</string>
  <string>everything.exe</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Apps_F {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Apps_F"]));
            }
            set {
                this["Apps_F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>battle.net.exe</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Apps_G {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Apps_G"]));
            }
            set {
                this["Apps_G"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>honeyview.exe</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Apps_H {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Apps_H"]));
            }
            set {
                this["Apps_H"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>mspaint.exe</string>
  <string>paintdotnet.exe</string>
  <string>IconWorkshop.exe</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Apps_I {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Apps_I"]));
            }
            set {
                this["Apps_I"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Apps_J {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Apps_J"]));
            }
            set {
                this["Apps_J"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" />")]
        public global::System.Collections.Specialized.StringCollection Apps_K {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Apps_K"]));
            }
            set {
                this["Apps_K"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>fontlab 8.exe</string>
  <string>fontlab.exe</string>
  <string>locknote.exe</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Apps_L {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Apps_L"]));
            }
            set {
                this["Apps_L"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>spotify.exe</string>\r\n  <string>aimp.exe</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Apps_M {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Apps_M"]));
            }
            set {
                this["Apps_M"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>NimbleText.exe</string>
  <string>NimbleSET.exe</string>
  <string>notepad.exe</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Apps_N {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Apps_N"]));
            }
            set {
                this["Apps_N"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Apps_U {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Apps_U"]));
            }
            set {
                this["Apps_U"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Apps_Y {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Apps_Y"]));
            }
            set {
                this["Apps_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>Zoom.exe</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Apps_Z {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Apps_Z"]));
            }
            set {
                this["Apps_Z"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dark")]
        public string Theme {
            get {
                return ((string)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsFocusNextEnabled {
            get {
                return ((bool)(this["IsFocusNextEnabled"]));
            }
            set {
                this["IsFocusNextEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableHotKey2 {
            get {
                return ((bool)(this["EnableHotKey2"]));
            }
            set {
                this["EnableHotKey2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192")]
        public int HotKey2 {
            get {
                return ((int)(this["HotKey2"]));
            }
            set {
                this["HotKey2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" />")]
        public global::System.Collections.Specialized.StringCollection Folder_0_Power {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Folder_0_Power"]));
            }
            set {
                this["Folder_0_Power"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("`")]
        public char Folder_0_Key {
            get {
                return ((char)(this["Folder_0_Key"]));
            }
            set {
                this["Folder_0_Key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>ApplicationFrameHost</string>
  <string>ShellExperienceHost</string>
  <string>SystemSettings</string>
  <string>TextInputHost</string>
  <string>Microsoft.Notes</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection BlockList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BlockList"]));
            }
            set {
                this["BlockList"] = value;
            }
        }
    }
}
